version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=admin@tempiemail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public
    labels:
      - "traefik.enable=true"

  web:
    build: ./apps/web
    env_file:
      - ./.env
    environment:
      - NEXT_PUBLIC_API_BASE=https://www.tempiemail.com/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-http.rule=Host(`www.tempiemail.com`) || Host(`tempiemail.com`)"
      - "traefik.http.routers.web-http.entrypoints=web"
      - "traefik.http.routers.web-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.web-static.rule=Host(`www.tempiemail.com`) && PathPrefix(`/_next/static`)"
      - "traefik.http.routers.web-static.entrypoints=websecure"
      - "traefik.http.routers.web-static.tls.certresolver=le"
      - "traefik.http.routers.web-static.priority=200"
      - "traefik.http.routers.web-static.service=web"
      - "traefik.http.routers.web.rule=Host(`www.tempiemail.com`) && !PathPrefix(`/api`) || Host(`tempiemail.com`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=le"
      - "traefik.http.routers.web.priority=10"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https?://tempiemail\\.com/(.*)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://www.tempiemail.com/$$1"
      - "traefik.http.routers.web.middlewares=www-redirect"
    depends_on:
      - api
    networks:
      - public

  api:
    build: ./apps/api
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`www.tempiemail.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.priority=100"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
      - "traefik.http.services.api.loadbalancer.server.port=4000"
      - "traefik.http.services.api.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.api.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.api.loadbalancer.responseforwarding.flushinterval=1s"
    depends_on:
      - postgres
      - redis
    networks:
      - public
      - private

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=tempiemail
      - POSTGRES_PASSWORD=tempiemail
      - POSTGRES_DB=tempiemail
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - private

  redis:
    image: redis:7-alpine
    networks:
      - private

  smtp:
    build: ./apps/smtp
    environment:
      - SMTP_DOMAIN=tempiemail.com
      - DB_HOST=postgres
      - DB_USER=tempiemail
      - DB_PASSWORD=tempiemail
      - DB_DATABASE=tempiemail
    ports:
      - "25:25"
    depends_on:
      - postgres
    networks:
      - private

volumes:
  db_data:
  traefik_letsencrypt:

networks:
  public:
  private:
